import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: "center",
        padding: 24,
    },
    title: {
        fontSize: 32,
        fontWeight: "800",
        color: "#2f855a",
        marginBottom: 8,
        letterSpacing: -0.5,
    },
    subtitle: {
        fontSize: 16,
        color: "#475569",
        marginBottom: 32,
        lineHeight: 22,
    },
    label: {
        fontSize: 14,
        fontWeight: "700",
        color: "#0f172a",
        marginBottom: 8,
    },
    input: {
        width: "100%",
        height: 50,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 8,
        paddingHorizontal: 16,
        fontSize: 16,
        backgroundColor: "#f1f5f9",
        marginBottom: 20,
        color: "#0f172a",
    },
    button: {
        backgroundColor: "#2f855a",
        height: 52,
        borderRadius: 8,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
        shadowColor: "#0f172a",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        elevation: 3,
    },
    buttonText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "700",
    },
    linkText: {
        marginTop: 24,
        textAlign: "center",
        color: "#3b82f6",
        fontSize: 14,
        fontWeight: '600',
        textDecorationLine: "underline",
    },
});
