import { StyleSheet } from "react-native"

export const donationStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: "#f8fafc",
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
		color: "#0f172a",
        marginBottom: 6,
		letterSpacing: -0.5,
    },
    subtitle: {
        fontSize: 15,
		color: "#475569",
        marginBottom: 16,
		lineHeight: 22,
    },
    searchContainer: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 16,
    },
    input: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 8,
        paddingHorizontal: 14,
        paddingVertical: 12,
		backgroundColor: "#f1f5f9",
		color: "#0f172a",
		fontSize: 15,
    },
    searchButton: {
        backgroundColor: "#2f855a",
        paddingHorizontal: 20,
        justifyContent: 'center',
        borderRadius: 8,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 2},
		shadowOpacity: 0.08,
		shadowRadius: 4,
		elevation: 2,
    },
    searchButtonText: {
        color: "#ffffff",
        fontWeight: '700',
		fontSize: 15,
    },
    map: {
        width: '100%',
        height: 260,
        borderRadius: 12,
		borderWidth: 1,
		borderColor: "#e2e8f0",
        marginBottom: 20,
    },
    nearbyTitle: {
        fontSize: 20,
        fontWeight: '800',
		color: "#0f172a",
        marginBottom: 12,
		letterSpacing: -0.3,
    },
    card: {
		backgroundColor: "#ffffff",
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 1,
    },
    foodBankName: {
        fontSize: 18,
        fontWeight: '700',
		color: "#0f172a",
    },
    distance: {
        marginTop: 4,
		fontSize: 13,
		color: "#94a3b8",
        fontWeight: '600',
    },
    address: {
        marginTop: 6,
        marginBottom: 12,
		fontSize: 14,
		color: "#475569",
		lineHeight: 20,
    },
    sectionTitle: {
		fontSize: 14,
        fontWeight: '700',
		color: "#0f172a",
        marginBottom: 6,
		textTransform: 'uppercase',
		letterSpacing: 0.5,
    },
    matchBox: {
        marginTop: 14,
        padding: 12,
        backgroundColor: "#e6fffa",
        borderRadius: 8,
		borderWidth: 1,
		borderColor: "#4CAF50",
    },
    matchTitle: {
        fontWeight: '700',
		color: "#2f855a",
		fontSize: 14,
        marginBottom: 4,
    },
    noMatch: {
        marginTop: 10,
        fontSize: 13,
		color: "#94a3b8",
		fontWeight: '500',
    },
    unavailableBox: {
        padding: 12,
        marginTop: 8,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 8,
		backgroundColor: "#f1f5f9",
    },
    unavailableTitle: {
        fontWeight: '700',
		color: "#475569",
		fontSize: 13,
        marginBottom: 4
    },
    unavailableText: {
		fontSize: 13,
		color: "#94a3b8",
        marginBottom: 10
    },
    linkButton: {
        backgroundColor: "#2f855a",
        paddingVertical: 10,
        borderRadius: 8,
        alignItems: 'center'
    },
    linkButtonText: {
        color: "#ffffff",
        fontWeight: '700',
		fontSize: 14,
    },
    error: {
		fontSize: 14,
		color: "#ef4444",
		fontWeight: '600',
        marginBottom: 12,
    }
})