import { StyleSheet } from 'react-native'

export const pantryStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
        padding: 20,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
		paddingTop: 8,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
		color: "#0f172a",
		letterSpacing: -0.5,
    },
    subtitle: {
		fontSize: 14,
        color: "#475569",
        marginTop: 2,
    },
    addButton: {
        backgroundColor: "#2f855a",
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
		shadowColor: "#0f172a",
		shadowOffset: { width: 0, height: 2},
		shadowOpacity: 0.08,
		shadowRadius: 4,
		elevation: 2,
    },
    addButtonText: {
        color: "#ffffff",
        fontWeight: '700',
		fontSize: 14,
    },
    foodList: {
        gap: 12,
    },
    foodCard: {
		backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: "#e2e8f0",
        shadowColor: "#0f172a", 
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 4,
        elevation: 1,
    },
    cardMainContent: {
        flex: 1,
        paddingRight: 16,
    },
    cardExpiryColumn: {
        alignItems: 'flex-end',
        justifyContent: 'center',
        width: 95,
    },
    foodName: {
        fontSize: 16,
        fontWeight: '700',
        color: "#0f172a",
        marginBottom: 4,
    },
    foodDetails: {
        color: "#475569",
        fontSize: 13,
		fontWeight: "500",
    },
    expiryLabel: {
        fontSize: 11,
        color: "#94a3b8",
        textTransform: 'uppercase',
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    expiryDate: {
        fontSize: 13,
        marginTop: 2,
        fontWeight: '700',
        color: "#0f172a",
    },
    emptyText: {
        textAlign: 'center',
        marginTop: 60,
		fontSize: 15,
		fontWeight: '500',
        color: "#94a3b8",
    },
    modalBackground: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: "rgba(15, 23, 42, 0.4)",
    },
    modalContainer: {
        backgroundColor: "#ffffff",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
		paddingBottom: 40,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '800',
		color: "#0f172a",
        marginBottom: 20,
		letterSpacing: -0.3,
    },
    optionButton: {
        borderWidth: 1,
        borderColor: "#e2e8f0",
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
		backgroundColor: "#ffffff",
    },
    optionTitle: {
        fontSize: 16,
        fontWeight: '700',
		color: "#0f172a",
    },
    optionDescription: {
        color: "#475569",
		fontSize: 13,
        marginTop: 4,
		lineHeight: 18,
    },
    input: {
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 8,
        padding: 14,
		fontSize: 15,
        marginBottom: 12,
		backgroundColor: "#f1f5f9",
		color: "#0f172a",
    },
    saveButton: {
        backgroundColor: '#2f855a',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 8,
    },
    saveButtonText: {
        color: "#ffffff",
        fontWeight: '700',
		fontSize: 16,
    },
    cancelButton: {
        padding: 16,
        alignItems: 'center',
    },
    cancelText: {
        color: "#475569",
		fontWeight: '600',
		fontSize: 14,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: 'rgba(255,255,255,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 999,
    },
    loadingText: {
        marginTop: 14,
        fontSize: 15,
        fontWeight: '700',
        color: "#0f172a",
    },
    datePickerSelectorButton: {
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 8,
        padding: 14,
        marginBottom: 16,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: "#f1f5f9",
    },
    datePickerSelectorText: {
        fontSize: 15,
        color: "#0f172a",
		fontWeight: '500'
    }
})